Autodesk/genetic-constructor

package.json, src/utils/environment/invariant.js, test/utils/invariant.spec.js
=> Add invariant and tests

src/containers/graphics/Intersection2d.js, src/containers/graphics/Line2d.js
Quick fix for hasProp function and lint errors
=> fix line2d class and fix lint errors

src/utils/generators/color.js
=> add anais colors to generator

test/middleware/api.js
=> add middleware tests for read/ write files

test/models/Instance.spec.js
=> add test for immutability

src/actions/blocks.js, src/containers/GlobalNav.js, src/containers/ProjectPage.js, src/containers/graphics/dnd/dnd.js, src/containers/graphics/mousetrap.js, src/containers/graphics/scenegraph2d/node2d.js, src/containers/graphics/views/constructviewer.js, src/containers/graphics/views/constructvieweruserinterface.js, src/styles/App.css, src/styles/Menu.css, src/styles/ProjectPage.css
Mainly useful because it fixes scrolled elements for mouse actions and drag and drop
=> Menus redux

src/index.js
@maxbates @dchandran 
Master fix, removes onion...let merge quickly.
=> fix master by removing onion

src/components/InspectorBlock.js, src/containers/Inspector.js
Adds multi-select for the inspector. Has ghost inspector test separately.
Would be nice to get in for Monday Demo @maxbates
=> Inspector multiselect

src/models/Block.js, src/models/Instance.js, src/models/Project.js, test/server/data/REST/blocks.js
=> use scaffolds in models

server/devServer.js
This url /version will return contents of VERSION file, when file is present. VERSION file will be written at docker-image-build-time and then is verified at deployment time.
=> Add logic to handle request for /version 

src/components/ProjectHeader.js, src/models/Block.js, src/models/Instance.js
Small tweaks:
- project page chrome - can't click "project" anymore. 
- blocks get color when created (my bad)
- instance model uses scaffold, not static object base
=> Projectpage chrome

README.md
Shows a build badge for the docker build image stored in quay.io.
=> Update README.md with docker image build status

src/components/Inventory/InventoryGroup.js, src/components/Inventory/InventoryGroupBlocks.js, src/components/Inventory/InventoryGroupSearch.js, src/components/Inventory/InventorySearch.js, src/containers/Inventory.js, src/inventory/egf/index.js, src/inventory/igem/index.js
fixes egf + igem search routes
adds Andrea parts under EGF parts (temporary)
=> Inventoryfix

src/components/InspectorBlock.js, src/components/Inventory/InventoryGroupBlocks.js, src/components/Inventory/InventoryGroupSbol.js, src/components/Inventory/InventoryGroupSearch.js, src/components/Inventory/InventoryList.js, src/components/ui/SymbolPicker.js, src/containers/Inventory.js, src/containers/graphics/scenegraph2d/glyphs/html/sbolglyph2d.js, src/inventory/andrea.js, src/inventory/egf/parseResults.js, src/inventory/examples/exampleWithAnnotations.js, src/inventory/igem/parseResults.js, src/inventory/sbol.js, src/middleware/search.js, src/models/Instance.js, src/reducers/blocks.js, src/reducers/index.js, src/schemas/Annotation.js, src/styles/Inspector.css
Update SBOL symbol data
fetch more data from iGEM, before displaying in inspector / drag-dropping
escape search string regex to prevent errors
better sequence length handling in inspector
updates to scaffolding to better allow prefixed IDs
show annotations in inspector, add example block
=> Inventory Fixes

src/containers/graphics/views/constructViewerCanvas.js
This was finished yesterday but the API changed after PR was created...and then I accidentally merged it. This needs to get approved and merged as quickly as possible to fix master.
=> update to new focus actions

src/containers/graphics/views/layoutconstants.js
If there is too much code here we can split it up.
Take your time and let me know if you need help reviewing this one.
=> normal weight text on nodes

src/containers/graphics/views/constructvieweruserinterface.js
it uses navigator.userAgent to identify user's OS type, if it is mac use meta key, otherwise, use ctrl key.
is works on windows, please test it on mac.
=> ctrl+click works on windows, please test it on mac

src/styles/InputSimple.css, src/styles/Inspector.css, src/styles/InventoryGroup.css, src/styles/InventorySources.css, src/styles/Menu.css, src/styles/ProjectHeader.css, src/styles/SidePanel.css, src/styles/variables.css
=> Font sizes

server/data/querying.js
=> search for user ID exact match in JSON

src/components/svgsbol.js, src/components/ui/SymbolPicker.js, src/images/sbolSymbols/templates/cds.svg, src/images/sbolSymbols/templates/insulator.svg, src/images/sbolSymbols/templates/operator.svg, src/images/sbolSymbols/templates/originReplication.svg, src/images/sbolSymbols/templates/promoter.svg, src/images/sbolSymbols/templates/protease.svg, src/images/sbolSymbols/templates/proteinStability.svg, src/images/sbolSymbols/templates/rbs.svg, src/images/sbolSymbols/templates/ribonuclease.svg, src/images/sbolSymbols/templates/rnaStability.svg, src/images/sbolSymbols/templates/terminator.svg, src/styles/Picker.css
Only changes the SBOL svg symbols and tweaks for the CSS for the SVG in the symbol picker. So review required.
=> new 1/2 pixel aligned SVG SBOL symbols and tweak css for smybol picker

src/components/InputSimple.js, src/styles/InputSimple.css, src/styles/Inspector.css
=> ui tweaks to inspector inputs

server/data/index.js, server/data/querying.js, src/components/Inventory/InventoryGroupProjects.js, src/components/Inventory/InventoryGroupSearch.js, src/components/Inventory/InventoryItem.js, src/components/Inventory/InventoryList.js, src/inventory/sbol.js, src/middleware/api.js, src/styles/InventoryGroup.css, src/styles/InventoryListGroup.css, src/styles/InventorySearch.css, src/styles/InventoryTabs.css, tools/start.js
tabs in inventory for projects
EGFAD-223
=> Inventory tabs

src/images/sbolSymbols/templates/promoter.svg, src/images/sbolSymbols/templates/terminator.svg
self merging so @jlachoff can review sbol symbols
=> replace two sbol symbols

server/data/index.js, server/data/permissions.js, server/data/persistence.js, server/data/querying.js, server/data/rollup.js, server/utils/errors.js, src/actions/blocks.js, src/components/Inventory/InventoryGroupProjects.js, src/components/Inventory/InventoryItem.js, src/constants/ActionTypes.js, src/middleware/api.js, src/reducers/blocks.js, test/server/data/REST/info.spec.js, test/server/data/rollup.spec.js
Support on Data API to get components of a block
Dragging constructs from inventory should work fine now. 
Future support for when we don't load the whole project into the store on toggling inventory tabs
=> Querying components

src/actions/blocks.js, src/components/Inventory/InventoryGroupSearch.js, src/inventory/egf/index.js, src/inventory/igem/index.js, src/inventory/igem/parseResults.js, src/models/Annotation.js, src/models/Block.js, tools/README.md
=> Bug squashes

server/data/querying.js
=> query from blocks with no sbol, show in inventory tab

src/containers/ProjectPage.js, src/store/undo/reducerEnhancer.js
=> Leave alert

src/components/GlobalNav/autosaveTracking.js, src/containers/GlobalNav.js, src/store/autosave/autosaveCreator.js, src/styles/AutosaveTracking.css, src/styles/GlobalNav.css, src/styles/Menu.css, src/styles/form.css, src/styles/userwidget.css, src/styles/variables.css
=> initial autosaving indicator... need UX review

server/data/rollup.js, test/server/data/rollup.spec.js
=> only save rollup if blocks and project are valid

src/components/authentication/signin.js, src/components/authentication/signup.js, src/containers/App.js, src/containers/GlobalNav.js, src/containers/graphics/dnd/dnd.js, src/containers/graphics/geometry/box2d.js, src/containers/graphics/scenegraph2d/userinterface.js, src/containers/graphics/views/constructviewer.js, src/containers/graphics/views/constructvieweruserinterface.js, src/containers/graphics/views/layout.js, src/styles/InventoryItem.css, src/utils/ui/uiapi.js
=> Egfad 345 338

.eslintignore, tools/start.js
time to start linting again! we're past 400 errors. not terrible, lets keep it from getting too gnarly.
once we have CI, intend to enforce linting, so this is your heads up
=> eslint ignore server/extensions/node_modules

plugins/convert/csv/convert.py, plugins/convert/csv/csv_import.py, plugins/convert/csv/genbank_import.py, plugins/convert/csv/index.js, plugins/convert/csv/package.json
Need to add tests. Will be in the next pull request.
=> Initial cvs import functionality and routes

src/containers/GlobalNav.js
=> save project before attempting to download genbank file

server/server.js
=> dont log webpack requests

plugins/convert/csv/csv_import.py, plugins/convert/genbank/genbank_export.py, plugins/convert/genbank/genbank_import.py, src/middleware/api.js, test/middleware/plugins.js
So the roundtrip NCBI Import -> Genbank Export -> Genbank Import works fine now.
=> Several changes so the Import and Export Genbank

src/containers/graphics/geometry/vector2d.js, src/containers/graphics/scenegraph2d/node2d.js, src/containers/graphics/scenegraph2d/nodetext2d.js, src/containers/graphics/views/constructviewer.js
Speed up text rendering in blocks by only rendering when changed.
=> Render perf

src/actions/projects.js, src/containers/graphics/views/constructviewer.js, src/middleware/api.js, src/models/Block.js, src/models/Project.js, src/reducers/projects.js, test/models/Block.spec.js, test/models/Project.spec.js
=> Project versioning

server/server.js, test-e2e/tests/import-dna-sequence.js, test/models/Project.spec.js
Remove old project/test url from import dna test as well.
=> body parser except in test env. 

src/components/ui/ColorPicker.js, src/containers/Inspector.js, src/containers/Inventory.js, src/styles/App.css, src/styles/Picker.css, src/styles/ProjectPage.css, src/styles/SidePanel.css, src/styles/ribbongrunt.css, src/styles/variables.css
=> Grunt accommodating

src/components/Inspector/ListOptions.js, src/images/roleSymbols/templates/noSymbol.svg, src/reducers/blocks.js, src/selectors/blocks.js, src/styles/ListOption.css
moves egf parts to store, and listOptions expects them to be in the store too
=> Egf in store

src/actions/blocks.js, src/components/InputSimple.js, src/components/Inspector/BlockSource.js, src/components/Inspector/InspectorBlock.js, src/components/Inspector/InspectorProject.js, src/components/Inventory/InventorySearch.js, src/schemas/Metadata.js, src/schemas/fields/validators.js, src/styles/ribbongrunt.css
Block names: 64 chars
Block Description: 1024 chars
Project Title: 256 chars
Project Description: 2048 chars
Search Box: 128 chars
=> limit length of text inputs for various important places

server/order/egf.js, server/order/index.js
update order flow to attach user before submit and send email, write file for testing
=> small order flow update - user info

package.json
@duncanmeech does this affect your sourcemaps?
=> use release flag to start server

src/components/importdna/importdnaform.js, src/containers/GlobalNav.js
prevent sequence import into fixed frozen constructs
=> internalize grunt errors for import dna form. 

package.json, plugins/convert/genbank/genbank_export.py, plugins/convert/genbank/genbank_import.py, server/data/persistence.js, server/utils/filePaths.js, server/utils/validation.js, src/schemas/Block.js, src/schemas/OrderParameters.js, test/plugins/genbank.spec.js, test/schemas/Block.spec.js, test/server/data/REST/blocks.spec.js, test/server/data/REST/fetch.spec.js, test/server/data/REST/info.spec.js, test/server/data/REST/project.spec.js, test/server/data/REST/sequence.spec.js, test/server/data/REST/versioning.spec.js, test/server/data/persistence.spec.js, test/server/data/querying.spec.js, test/server/data/rollup.spec.js, test/store/autosaving.js, test/utils/rollup.js, tools/setup.js
There were issues with rules.role. All fixed. Tests log:
320 passing (14s)
22 pending
1 failing
1) Store Autosaving marks dirty when in between throttles:
Uncaught AssertionError: not dirty after first save
at [object Object]._onTimeout (autosaving.js:95:9)
=> Fixed Genbank I/O. All unit tests but one pass now.

plugins/convert/import.js, server/data/index.js, server/data/permissions.js, server/data/persistence.js, server/data/querying.js, server/data/versioning.js, server/order/index.js, server/server.js, server/utils/errorHandlingMiddleware.js, server/utils/fileSystem.js, test/middleware/rollup.js, test/server/data/REST/info.spec.js, test/server/data/REST/versioning.spec.js, test/server/data/persistence.spec.js
project.version is written after the commit
userId used as author when init + save project
several fixes + cleanups to server filesytem utils etc.
=> Persist project version

src/components/Inspector/InspectorBlock.js, src/components/Inventory/InventoryConstruct.js, src/components/Inventory/InventoryItem.js, src/components/Inventory/InventoryItemBlock.js, src/components/ui/Toggler.js, src/inventory/andrea/templates.js, src/styles/BasePairCount.css, src/styles/Inspector.css, src/styles/InventoryItem.css
template metadata shown in inspector
templates show up in inventory properly
=> Template inspector

server/data/permissions.js, server/data/persistence.js, server/data/querying.js, server/order/index.js, src/actions/orders.js, src/actions/projects.js, src/components/Inspector/InspectorBlock.js, src/components/Inventory/InventoryProject.js, src/containers/Inspector.js, src/containers/ProjectPage.js, src/middleware/order.js, src/models/Order.js, src/store/instanceMap.js, src/styles/Inspector.css
orders show in inspector, can open in modal
Middleware for fetching orders working better
orders in instance cache
includes #499
=> Inspector orders

src/components/Inspector/BlockNotes.js, src/components/Inspector/InspectorBlock.js, src/components/Inspector/InspectorProject.js, src/components/Inspector/InspectorRow.js, src/components/Inspector/InspectorRowHeading.js, src/components/Inspector/OrderList.js, src/containers/Inspector.js, src/styles/BlockNotes.css, src/styles/Inspector.css, src/styles/InspectorRow.css, src/styles/OrderList.css
puts orders in the inspector for projects
inspector components delegate much better, much cleaned up
=> Orders inspector

misc/404.html, misc/readme.txt, misc/ua.html
See readme.txt in the /misc folder. Same folder has the HTML source for both pages.
=> offline and 404 pages with readme.txt

plugins/convert/genbank/genbank_export.py
Some tests are failing, but have no relationship with this PR:
TEST FAILURE: 3 assertions failed, 513 passed (13m 1s)
✖ deleteproject
- Test that we can delete a construct via its context menu
Testing if element .construct-viewer occurs on the page 29 times. - Expected "29" but got: "1"
✖ template-order-preview
- Verify we can order all templates
Testing if element .order-button occurs on the page 29 times. - Expected "29" but got: "0"
✖ template-order
- Verify we can order all templates
Testing if element .order-button occurs on the page 29 times. - Expected "29" but got: "0"
=> Export -> Import roundtrip was failing for filler blocks. Fixed.

plugins/convert/genbank/convert.py, plugins/convert/genbank/genbank_export.py, plugins/convert/genbank/genbank_import.py
There were a few different issues with the sample file.
Color should be maintained for annotations now.
Order Test Fails!
TEST FAILURE: 1 assertions failed, 520 passed (11m 23s)
✖ template-order
- Verify we can order all templates
Testing if element .order-button occurs on the page 29 times. - Expected "29" but got: "0"
=> Exports the sample project now.

server/order/index.js, src/containers/orders/constructpreview.js, src/containers/orders/ordermodal.js, src/selectors/blocks.js, src/utils/generators/orderConstructs.js
fixes orders erroring because node has stack overflow
=> orders generated using less time + memory, page2 of dialog much zippier

src/components/Inventory/InventoryConstruct.js, src/components/Inventory/InventoryItem.js, src/containers/Inspector.js, src/selectors/focus.js
=> Focus notforce

server/auth/userSetup.js, server/order/index.js, src/actions/orders.js, src/actions/ui.js, src/components/GlobalNav/autosaveTracking.js, src/components/Inspector/BlockSource.js, src/components/Inventory/InventoryProject.js, src/components/aboutform.js, src/components/modal/SaveErrorModal.js, src/components/ui/Spinner.js, src/constants/ActionTypes.js, src/containers/App.js, src/containers/ProjectPage.js, src/containers/orders/checkbox.js, src/containers/orders/constructpreview.js, src/containers/orders/page1.js, src/images/ui/offsiteLink.svg, src/inventory/igem/parseResults.js, src/reducers/ui/modals.js, src/schemas/OrderParameters.js, src/schemas/Rules.js, src/store/saveState.js, src/styles/BlockSource.css
=> Failed saves

server/auth/userSetup.js, server/order/index.js, src/actions/orders.js, src/components/Inspector/BlockSource.js, src/components/Inventory/InventoryProject.js, src/components/ui/Spinner.js, src/containers/ProjectPage.js, src/containers/graphics/views/layout.js, src/containers/orders/checkbox.js, src/containers/orders/constructpreview.js, src/containers/orders/page1.js, src/images/ui/offsiteLink.svg, src/inventory/igem/parseResults.js, src/models/Block.js, src/schemas/OrderParameters.js, src/schemas/Rules.js, src/styles/BlockSource.css
=> Filler  - setting color doesn't change name

src/containers/graphics/views/constructvieweruserinterface.js
( although you can still select a block by dragging a rectangle around the options which is nice ).
=> selecting an option does not select the block

plugins/convert/genbank/genbank_import.py, test/plugins/genbank.spec.js
Fixed bug where some blocks showed the wrong length.
Fixed the genbank unit tests.
=> Length of the sequence is imported correctly

src/images/roleSymbols/templates/null.svg
=> add missing file

.github/ISSUE_TEMPLATE.md
for when people report issues using Github
=> add a github issue template

src/components/Inventory/InventoryGroupRole.js
=> scrolling on inventory Role section

server/order/index.js, src/components/Inspector/InspectorBlock.js, src/containers/Inspector.js, src/containers/Inventory.js, src/styles/Inspector.css, src/styles/InspectorRow.css, src/styles/SidePanel.css
=> Misc UI fixes

src/selectors/blocks.js, src/styles/BlockNotes.css, src/styles/Inspector.css
=> (fix) api.focus.focusGetBlockRange()

server/extensions/package.json
=> add seq-viewer to extensions

src/actions/ui.js, src/components/okcancel.js, src/containers/App.js, src/containers/GlobalNav.js, src/containers/ProjectPage.js, src/reducers/ui/modals.js
Address prop type errors
move some project specific modals into project page
Bug Fix
EGFAD-855 # close
None user facing
Some components are moved from App -> project page
=> Console errors

src/inventory/ncbi/index.js, src/styles/InventoryListGroupAction.css
NCBI search results sorted by relevance
Feature
EGFAD-631 #close sorted!
=> inventory search by relevance @ NCBI

src/styles/InventoryItem.css
Align text in inventory items with an image
Bug fix
=> Center align inventory text which has image

server/extensions/native/csv/index.js, test-e2e/tests/import-csv-file.js, tools/auth-stack.js
Add import / export route prefixes to csv router, csv import works better
Bug Fix
EGFAD-935 #done
=> csv router has import/export routes

extensions/clientAndServer/package.json, extensions/simpleWidget/README.md, extensions/simpleWidget/package.json, extensions/testClient/package.json, extensions/webpacked/README.md, extensions/webpacked/package.json, server/extensions/package.json, src/components/ProjectDetail.js, src/extensions/clientRegistry.js, src/extensions/regions.js, test/extensions/REST.js
Rename extension region
Change
EGFAD-939
Renames a region for extensions
EGFAD-939 #done
=> rename sequenceDetail to projectDetail

src/components/Menu/Menu.js, src/components/Menu/PopupMenu.js
Menus timeout and disappear on mouse-leave after 300ms
Feature
EGFAD-923
=> menus dont dissappear automatically, they have a timeout

src/components/importdna/importdnaform.js
sequence form responds to enter even when focus in textarea
=> submit sequence for on enter, even when focus in text area

tools/start.js
=> debounce runServer() in build scripts on file changes.

tools/auth-stack.js
update auth stack script for docker 1.12, expects docker running
Build
need docker 1.12
=> update auth stack script for docker 1.12, expects docker running

.travis.yml
=> add before install script for travis

server/extensions/native/genbank/index.js
Added a route to fix the e2e test import-export-genbank.
bug fix
None
=> Added route to fix e2e tests. Fix provided by Max.

package.json, src/models/Block.js, src/schemas/Sequence.js, test/models/Block.spec.js
Sequence trimming - specify start / end for sequences
feature
na
updates block.getSequence()
adds block.setSequenceTrim()
adds block.getSequenceLength()
=> Sequence trim

src/actions/blocks.js, src/models/Block.js, src/selectors/blocks.js
block selector to check if top level construct
check if top-level when marking template / authoring
prevent adding template as component in actions
=> better checks when marking template / authoring, in actoins

data/egf_parts/templateUtils.js
in egf project, position parts have role in rules, not in metadata
fix - data model
EGFAD 1063
=> metadata.role -> rules.role

server/extensions/native/csv/convert.js, server/extensions/native/csv/index.js, server/extensions/native/genbank/convert.js, server/extensions/native/genbank/index.js
blocks are wrapped in a construct if they have no children when added to a project in Genbank / CSV import
This is so they do not show up as a top-level construct that is empty, even though they have sequence etc.
Fix
n/a
=> Import constructs

.travis.yml
comment out sauce labs integration from travis (until its working)
Fix
=> remove sauce from travis CI

src/actions/blocks.js, src/components/Inspector/CSVFileDrop.js, src/components/Inspector/InspectorBlock.js, src/components/Inspector/ListOptions.js, src/components/importpartscsv/importpartscsv.js, src/components/ui/Checkbox.js, src/containers/Inspector.js, src/containers/graphics/views/constructviewer.js, src/containers/graphics/views/layout.js, src/selectors/blocks.js
fix lint issues as we expect CI to pass
fix
=> fix all outstanding lint issues

README.md
Add Travis CI build tag to readme
feature
none
=> Add build tag

src/reducers/blocks.js
Fix blocks reduces, master broken until merged.
fix
=> fix blocks reducer, which fixes two failing e2e tests

src/containers/Inspector.js, test-e2e/fixtures/homepage-register.js, test-e2e/nightwatch.js, test-e2e/tests/export-list-blocks.js, test-e2e/tests/forgot-reset.js, test-e2e/tests/homepage.js, test-e2e/tests/import-export-genbank-file.js, test-e2e/tests/undo-redo.js
nightwatch fixtures run at port 3000 
test fix
none?
=> fix url to 3000 for nightwatch tests

server/extensions/package.json, server/onboarding/userConfigDefaults.js
Switch to the new NPM module for the sequence viewer
=> switch to new NPM module for genome designer

src/components/Inspector/ListOption.js, src/components/Inspector/ListOptions.js, src/components/modal/ExtensionPicker.js, src/containers/Inventory.js, src/containers/graphics/views/constructvieweruserinterface.js, src/extensions/clientRegistry.js, src/reducers/user.js, src/styles/ListOption.css, src/styles/ListOptions.css
Can toggle all list options
can delete list options when authoring
fix overflow of long names of list options
fix an caught bug in construct rendering
feature + fix
none
close #819 
close #976
=> Authoring ui fixes

src/containers/graphics/views/constructviewer.js
hide order button unless all blocks have a source and it is EGF (pending more foundries)
fix
none
=> hide order button if source undefined, and not all sources egf

docs/installation/installation.md
note some specific versions on the install docs
docs
=> note some specific versions on the install docs

server/data/persistence.js, server/data/rollup.js, server/onboarding/onboardNewUser.js, server/utils/fileSystem.js, test/server/data/persistence.spec.js, test/server/onboarding.spec.js
onboarding is slightly faster because...
can skip validation on project / block write
adds test for onboarding timing
fix
none
=> Slightly faster Onboarding + test

extensions/example-python/client.js, extensions/example-python/helper.py, extensions/example-python/package.json, extensions/example-python/router.js
example extensions which calls an external script
example
=> Python extension

src/containers/orders/constructpreview.js, src/containers/orders/input.js, src/containers/orders/page1.js, src/containers/orders/updown.js, src/styles/form.css, src/styles/ok-cancel-form.css, src/styles/ribbongrunt.css
Fix CSS warnings on build and fix console warnings about prop types / isRequired in order form.
=> Fix warnings

docs/installation/installation.md
clean up installation notes
docs
=> Clean up installation notes

extensions/example-python/client.js, extensions/example-python/helper.py, extensions/example-python/package.json, extensions/example-python/router.js, server/extensions/package.json, server/extensions/pruneNodeModules.js
uses biopython in example python extension
fix
=> Better python example

docs/extensions/walkthroughs.md, extensions/example-python/README.md, extensions/example-python/client.js, extensions/example-python/package.json, extensions/example-python/router.js, extensions/example-python/walkthrough.md, server/server.js
- walkthrough to create simple python extension
- update server docs to latest
docs
=> add walktrhgouh for python extension 

src/components/genbank/import.js, src/components/importpartscsv/importpartscsv.js
Links for csv templates were out of date - this is fixed here.
bug fix
None
close #1007
=> csv documentation update 

src/components/authentication/register.js
Fix state of submit button in register form when TOS checkbox is changed.
=> make submit button change state when TOS is checked

CONTRIBUTING.md, README.md, docs/extensions/README.md
update readme with links, and contribution docs
docs
none
=> Open-sourcing doc updates

extensions/example-codon-optimization/README.md, extensions/example-codon-optimization/index.js, extensions/example-codon-optimization/package.json
adds an example extension which naively optimizes a sequence
example
=> Example Codon Optimization Extension

src/styles/Picker.css
Picker appears above list items
UI fix
none
close #958
=> Picker appears above list items

package.json, server/server.js
enable deflate / gzip compression across the app server
feature
none anticipated
close #1002
=> enable compression

src/reducers/index.js, src/store/autosave/autosaveInstance.js, src/store/configureStore.js, src/store/undo/reducerEnhancer.js, test/actions/blocks.js, test/components/Inventory.spec.js
so that we can create multiple stores in tests, needed to get rid of some singletons and add dynamic creation of store.
fix
none
=> Support for multiple store instances

src/containers/homepage.js
=> block internet explorer users from signing in

server/data/persistence/sequence.js
sequences were showing DOES_NOT_EXIST, was trying to fetch remotely when shouldnt have
temp fix
=> force local sequences

src/components/Inventory/InventorySearchResults.js
stash block on search, including for single blocks, so that clones without error
fix
none
closes #1068
=> Fix block search drag-drop

server/auth/local.js
Can pass env var `LOCAL_AUTH_NEW_USERS=true` to force a new ID for every login (e.g. when running e2e tests) - users will start with a clean slate, and not have the projects etc. of previous logins.
Note, will not save ID to email or anything - you will get a new log in every time you log in. Change user information will not generate a new UUID.
feature
close #1069
=> allow forcing of new user id across every login, for e2e tests

src/containers/homepage.js, src/reducers/ui/inspector.js, src/utils/ui/localstorage.js
=> remove local storage item if cannnot be parsed, add default for inventory

src/middleware/reporting.js
when report issues from the app, to match new github issue label
fix
=> Update reporting error issue label

server/extensions/package.json
Changed GSL extension repo in server/extensions/package.json
None. Luckily github seems to handle it fine.
=> GSL extension moved to autodesk-bionano

test-e2e/nightwatch.js
allow setting nightwatch URL via env var `NIGHTWATCH_URL`
feature
-
=> allow setting nightwatch URL via env var

server/data/files/agnosticFs.js, server/data/routerProjectFiles.js, test/server/data/files/agnosticFs.spec.js
can write empty files (i.e. if pass `''`, not `undefined`)
fix
none
=> change so can write empty file

package.json, storage-ext/package.json
Bump versions for the DB Release
=> Db release

server/data/middleware/db.js, server/data/persistence/blocks.js
block storage API had extra slashes, only showe up in production. remove them and warn.
fix
-
=> Block api fix

.travis.yml, Dockerfile, package.json, tools/checks.js, tools/copy.js
Move to node v6, current LTS branch
update
use node 6 instead of node 4. upgrade your system!
#770 
#1050
=> update to node 6 LTS branch

.travis.yml, Dockerfile, package.json, src/middleware/csv.js, src/middleware/genbank.js, src/utils/timeLimit.js, tools/checks.js, tools/copy.js
Note - includes #1203 
timeout file uploads after 10 secods
feature
none
#1179
=> file upload timeout @ 10s

src/actions/projects.js
=> hide the project undefined banner

src/components/ExtensionView.js, src/components/ui/Spinner.js, src/styles/ExtensionView.css, src/styles/animations.css
proper loading indicator for extension view
feature
none
close #1005
=> add loading indication for extensions

server/server.js, src/components/Inspector/InspectorBlock.js, test/setup.spec.js, tools/run.js, tools/runServer.js, tools/start.js
- catch error where palette is undefined
- Wrap start tool in try-catch, kill process if server fails to start
fix
--
--
--
=> Start tool and palette

src/actions/projects.js
in addition to if project ID not defined.... dont show th ebanner if the project was never laoded
fix
none
=> hide could not save banner if project is not loaded

data/egf_parts/connectorList.json, data/egf_parts/partList.json, server/data/files/agnosticFs.js, server/data/middleware/s3.js, server/data/persistence/sequence.js, server/data/routerSequences.js, server/extensions/native/_shared/importMiddleware.js, server/extensions/native/genbank/convert.js, server/extensions/native/genbank/genbank_export.py, server/extensions/native/genbank/index.js, src/components/Inventory/InventoryItem.js, src/components/Inventory/InventoryRoleMap.js, src/inventory/ncbi/index.js, src/models/Block.js, src/schemas/Rollup.js, src/schemas/Sequence.js, test/extensions/genbank.spec.js, test/extensions/genbankMiddleware.js, test/server/data/REST/sequence.spec.js, test/server/data/persistence/S3.spec.js, test/setup.spec.js, test/templates/EGF.js, tools/clean.js, tools/lib/cp.js, tools/setupFiles.js, tools/startDb.js
- proper clearing of s3 buckets, avoid race conditions in travis, differentiation of travis builds
- EGF sequences properly written on start
- Genbank conversions write sequences
- genbank zip-file writes dont restart server with webpack
- conversions return rollups, not custom data structure
- handle no sequence in genbank import
- by kind tab loads block properly
- remove hex colors from egf parts
- better error logging from s3
fix
no
=> Db branch fixes

README.md, storage-ext/README.md, storage-ext/docs/api/ADMIN.md, storage-ext/docs/api/BLOCKS.md, storage-ext/docs/api/ORDERS.md, storage-ext/docs/api/PROJECTS.md, storage-ext/docs/api/SNAPSHOTS.md
This is a first cut at extensive documentation of the Storage API.
These commits are **ONLY** Markdown.
None
#1127
=> Storage docs

server/extensions/native/_shared/importMiddleware.js, server/extensions/native/csv/index.js, server/extensions/native/genbank/index.js, src/components/Inspector/ListOptions.js, src/middleware/csv.js, test/extensions/csv.js, test/extensions/genbank.spec.js, test/models/Block/Constructor.spec.js, tools/copy.js, tools/run.js
unsets block.projectId at end of import conversions, so it is null when returned to the client
fix
If you try to make a rollup model from what is returned, it will error
=> Csv + GB Conversions unset block.projectId

src/containers/LandingPage.js, src/public/landing_page_content/index.html
=> Don't block new tabs

src/public/landing_page_content/index.html
Link forwarding fix for landing page
=> create valid token

src/containers/LandingPage.js, src/public/landing.html, src/public/landing/custom.css, src/styles/LandingPage.css
Update styles from improved mobile landing page. 
Display tool name on modal background.
UI
=> Landing mobile

server/utils/captcha.js, src/actions/user.js, src/components/authentication/RegisterForm.js, src/middleware/auth.js, src/public/landing.html, src/public/landing/custom.css, test/actions/user.js
Verify captcha works as intended
signout -> just to landing page
Sick fade effect on trigger modal
leave 'darwin magic' in production, needed for QA valdiation. cannot register in prod.
feature
=> Landing captcha verified

src/actions/orders.js, src/containers/orders/ordermodal.js, src/containers/orders/page1.js, src/models/Order.js
Fix when changing container type, properly sets active indices
fix
=> Order container type change fix

src/components/Inspector/InspectorBlock.js
=> Palette name fix

src/components/Inspector/InspectorBlock.js, src/styles/Inventory.css, src/styles/InventoryGroup.css, src/styles/InventoryGroupRole.css, src/styles/InventorySearch.css, src/styles/Label.css
=> Inspector panel fixes

server/server.js
ignore query params for landing page
fix
close #1414
=> ignore query params for landing page

src/containers/Inspector.js, src/containers/SectionIcon.js, src/styles/SectionIcon.css
=> Panel navigation fixes

src/components/ProjectHeader.js, src/components/ribbongrunt.js, src/containers/Inspector.js, src/containers/SectionIcon.js, src/styles/SectionIcon.css, src/styles/ribbongrunt.css, src/styles/variables.css
css blarg
....also closes the extensions panel when closing all panels from project menu
=> Exciting new changes to the ribbon grunt

src/components/ProjectHeader.js, src/components/ribbongrunt.js, src/containers/Inspector.js, src/containers/SectionIcon.js, src/styles/Inspector.css, src/styles/SectionIcon.css, src/styles/ribbongrunt.css, src/styles/variables.css
Rearrange inspector so title no scrolly
=> Inspector title area

src/components/ProjectHeader.js, src/components/ribbongrunt.js, src/containers/Inspector.js, src/containers/SectionIcon.js, src/containers/graphics/views/constructviewer.js, src/styles/Inspector.css, src/styles/SceneGraphPage.css, src/styles/SectionIcon.css, src/styles/inter-construct-droptarget.css, src/styles/ribbongrunt.css, src/styles/variables.css
Last drop target has a much larger drop area. Color changes to focused construct viewer background. Remove top line on construct viewer.
=> Canvas drop target redux

server/extensions/package.json
Pin the GSL editor version so we can work on the extension making breaking changes without breaking QA and Production.
fix
none
This needs to go out to QA and PROD *BEFORE* we rollout the UX changes which currently require changes to the GSL editor.
#1314
=> pin GSL version to support better dev process

src/models/Rollup.js, src/schemas/Metadata.js, src/schemas/Rollup.js, test/models/Rollup.spec.js, test/schemas/Rollup.js
- updates project on load + rollup creation
- will run each time needed, until saved again 
fix
na
=> update project on creation / load as needed

src/components/Menu/MenuOverlay.js, src/components/toolbars/title-and-toolbar.js, src/containers/graphics/views/constructviewer.js, src/containers/graphics/views/constructvieweruserinterface.js, src/containers/graphics/views/layout.js
=> Construct context menu

src/components/Inspector/InspectorBlock.js, src/components/Inspector/InspectorGroupExtensions.js, src/components/ProjectHeader.js, src/containers/App.js, src/containers/graphics/views/constructviewer.js, test-e2e/tests/hide-nested-blocks.js, test-e2e/tests/inspector-extensions.js
Misc small features as noted in: https://zube.io/autodesk/genome-designer/c/1447
=> Ui e2e misc

src/styles/ok-cancel-form.css
( includes delete project dialog )
=> fix text color on ok-cancel dialog

src/containers/Inspector.js, src/styles/BlockSource.css
=> change inspector/information title according to item being inspected

src/components/ui/ColorPicker.js, src/components/ui/SBOLPicker.js, src/styles/ColorPicker.css
( hover text for colors and symbols + white outline for selected colors )
=> Color symbol text

src/containers/graphics/scenegraph2d/glyphs/html/listitemglyph2d.js, src/containers/graphics/scenegraph2d/glyphs/html/roleglyph2d.js, src/containers/graphics/views/layout.js
=> hidden blocks 50% darker if displayed

src/components/authentication/ForgotForm.js
forgot form complains when you try to submit. this fixes it.
=> fix for forgot form

server/extensions/native/csv/convert.js, server/extensions/native/genbank/convert.js, src/components/Inspector/BlockSource.js, src/inventory/ncbi/index.js, src/schemas/BlockSource.js
- genbank and csv save block.source.file
- prefer NCBI url to genbank file
- update block.source schema
fix
close #1466
=> Update block.source for NCBI

server/errors/lastDitchErrorMiddleware.js, src/models/Rollup.js, src/schemas/SchemaClass.js
- upgrade project rollups without a schema listed (more backwards compatible)
- better logging for validation errors
fix
=> Better handle upgrading of projects with no schema listed

src/components/Inspector/InspectorGroupHelp.js, src/styles/InspectorGroupHelp.css
=> ensure all links have an href to ensure correct cursor

src/components/Inspector/InspectorGroupHelp.js, src/containers/graphics/views/constructviewer.js, src/styles/InspectorGroupHelp.css
Hidden block toggling from view menu
=> Hidden block menu item

src/styles/InspectorGroupExtensions.css
https://zube.io/autodesk/genome-designer/c/1262
=> css for extensions panel

src/components/authentication/ResetForm.js
re-add necessary function to reset password
form was working, but showed error + didn't show feedback message
feature
=> fix reset form (bad merge?)

src/components/ProjectDetail.js, src/containers/graphics/views/constructviewer.js
Show / Hide sequence viewer from various menus
=> Inspect sequence

src/actions/blocks.js, src/containers/Inspector.js, src/containers/graphics/views/constructViewerCanvas.js, src/schemas/Parent.js, src/schemas/fields/validators.js, test/models/Project.spec.js, test/schemas/_examples.js
projects weren't loading because they did not conform to new schema constraints. this relaxes those rules, which are only really necessary BEFORE we add publishing support.
=> Hotfix - revert schema validation, pending DB migration

.gitignore, src/components/Inspector/InspectorBlock.js, src/components/toolbars/title-and-toolbar.js, src/containers/orders/constructpreview.js, src/reducers/ui/inspector.js, test-e2e/tests/deleteproject.js, test-e2e/tests/select-empty-blocks.js, test-e2e/tests/symbol-picker.js
Help panel in inspector open by default
=> Open help on register

src/inventory/ncbi/index.js
=> NCBI url is set on summary (e.g. inspect result)

src/components/ProjectDetail.js
Duplicate child snuck into project details. This removes.
=> fix dup key in project details

src/components/Inspector/InspectorGroupFeedback.js, src/middleware/reporting.js
=> connect feedback to API in addition to heap

src/styles/InspectorGroupExtensions.css
force break words in extensions panel
=> force break words in extensions properties panel

server/data/persistence/orders.js, server/order/router.js
more logging (under DEBUG=cosntructor:order and constructor:data:persistence:orders) for ordering
logs
=> more logging for orders

server/extensions/native/genbank/convertChild.js, server/extensions/native/genbank/genbank_export.py, src/components/ProjectHeader.js, src/containers/graphics/views/constructviewer.js
- Genbank downloads work for list blocks with one option
- show banner when download begins
fix
close #982
=> fix genbank downloads for list blocks with one option

src/containers/orders/permutations.js, src/containers/routenotfound.js, src/public/404.html
=> 404 page should be all white text

package.json
This release is going out now.
=> merge the v0.9.3 release tag back into master

src/components/GlobalNav/GlobalNav.js, src/components/Inspector/InspectorBlock.js, src/components/RoleSvg.js, src/components/toolbars/title-and-toolbar.js, src/components/ui/SBOLPicker.js, src/containers/graphics/scenegraph2d/backbone2d.js, src/containers/graphics/scenegraph2d/glyphs/html/backbone-glyph.js, src/containers/graphics/scenegraph2d/glyphs/html/roleglyph2d.js, src/containers/graphics/scenegraph2d/node2d.js, src/containers/graphics/scenegraph2d/userinterface.js, src/containers/graphics/views/constructviewer.js, src/containers/graphics/views/constructvieweruserinterface.js, src/containers/graphics/views/layout.js, src/containers/graphics/views/layoutconstants.js, src/containers/orders/constructpreview.js, src/content/index.pug, src/inventory/roles.js, src/styles/SceneGraphPage.css, src/styles/title-and-toolbar.css, test-e2e/fixtures/click-nth-block-bounds.js, test-e2e/fixtures/click-popmenu-nth-item.js, test-e2e/fixtures/open-nth-block-contextmenu.js, test-e2e/fixtures/select-nth-block.js, test-e2e/tests/circular-constructs.js, test-e2e/tests/select-empty-blocks.js
=> Circular constructs

src/actions/projects.js
gsl was trying to change frozen constructs (well, projectRemoveConstruct was)
fix
=> fix for GSL trying to update frozen constructs

src/components/ui/PalettePicker.js, src/styles/PalettePicker.css, test-e2e/tests/palette-picker.js
Palette picker as per this spec.
https://zpl.io/Z1KfR5n
=> New palette picker

src/actions/projects.js, src/components/GlobalNav/autosaveTracking.js, src/components/Inventory/InventoryGroupRole.js, src/middleware/projects.js
re-enable failed to save dialog
clearer feedback on project autosaving
fix error dropping block to show dialog
fix
-
=> Autosave fixes

package.json
Brings the last release tab back into Master
=> Merge QA back into Master before next release

src/public/landing/custom.css
=> move cookie banner down to not block sign-in

data/egf_parts/addToProject.js, data/egf_parts/connectorList.json, data/egf_parts/index.js, data/egf_parts/partList.json, data/egf_parts/templateUtils.js, src/components/Inspector/InspectorBlock.js, src/containers/Inventory.js, src/models/Block.js
- script for generating EGF project as normal project, update to fixed (not frozen)
- remove the templates tab for now
- update inspector so all blocks can be protected / unprotected
feature
no templates tab
=> Updates for publishing EGF project

src/public/landing.html, src/public/landing/custom.css
- switch color for more attention
- adjust wording the link
=> adjust wording and final style for banner

server/extensions/native/genbank/genbank_import.py
If the journal has "SnapGene" and "Vector", the name of the block comes now from the "label" qualifier, and the description concatenates "note", "product" and "gene".
Also sped up import by 30%.
Should be none
I COULD NOT RUN THE APP LOCALLY SO COULD NOT TEST WITH THE APP, but tested the conversion in isolation and verified that it does not change anything for non-snapgene files.
=> Added a better import for snapgene vector nti exports

src/utils/color/paletteBright.js, src/utils/color/paletteNature.js, src/utils/color/palettePastel.js
I updated the color values on 3 of our color files so we can test out the new palettes Malte gave me.
UI
?
Just changed the hex values. I left the previous ones in, but commented them out. I guess that was unnecessary...
=> Jlachoff color experiments1

src/components/Inventory/InventoryProjectTree.js, src/components/modal/DeleteProjectModal.js, src/reducers/ui/modals.js
Project deletion was not properly passing in the ID of the project to delete. fixed. 
fix
=> Delete project - works for right click

src/public/landing.html
=> fix youtube link

package.json
=> QA -> master (v0.11)

commons/app/components/Header.js, commons/app/components/Tag.js, server/server.js, src/public/landing.html, test/extensions/genbank.spec.js, tools/checks.js, tools/start.js, tools/webpack.config.js
url fixes
homepage accessile when logged in with query param `forceLanding=true`
hide empty tags in commons
fix
no
close #1753
=> UI fixes for commons

extensions/blast/blockMenuItem.js
sequence was not properly unset... so you had a list block with sequence
fix
=> remove sequence on blast jobs

commons/app/components/ConstructRadial.js, commons/app/components/Footer.js, commons/app/components/Project.js, src/constants/links.js
fix social media links
handle no defined list block in construct radial
(Was affecting rendering of one of joe's projects)
fix
=> fix links + Commons Radial construct

extensions/blast/blockMenuItem.js, extensions/blast/jobProcessor.js, extensions/blast/parseJson.js, server/data/permissions.js, server/jobs/jobQueueDelegator.js, src/components/Inventory/InventoryItem.js, src/graphics/views/ConstructViewerJob.js
Better handle failures for jobs, handle when BLAST queries are unsuccessful
fix
no
=> Blast fix - handle no results + handle failure better

src/components/modal/PublishForm.js, src/constants/links.js
=> update CCO link

.gitignore
As the title says
Minor config change
=> Ignore silver searcher and sublime text projects

package.json, tools/webpack.config.js
Merge version change and production complication bug fix back into `master`
=> Merge v0.12.1 release back into master
