Autodesk/genetic-constructor

Dockerfile, devServer.js, src/models/Instance.js
Added support to run within a Docker container. Minor changes which were:
-- add Dockerfile. The docker container inherits from node v4 container, so that is how node versioning is handled.
-- fix reference to UUID.js  in code to match case of file name. On Ubuntu this was failing due to case sensitivity.
-- change logic for determining the run-time port to be, in order, derived from: command line, environment, default port.
-- change the host name used when setting up the listening port. Changed from 'localhost' to '0.0.0.0'. The latter syntax results in the node server listening on all network addresses, while localhost results in only listening on the loopback address, (and was thus not listening on the other ip address(es) of the machine).
=> Added docker support

docker-compose-prod.yml, docker-compose.yml
ENTRYPOINT is retained with docker-compose uses command: 
So if a 'command' command is used in docker-compose and the desired command is  'npm run start' and the Dockerfile ENTRYPOINT contains "npm", then docker-compose command entry should be: 'run start'. Removed the command override in the compose file since it did not differ from the default.
=> fixed CMD launch error in compose file

src/actions/blocks.js, src/constants/ActionTypes.js, src/middleware/api.js, src/reducers/blocks.js, test/actions/blocks.js, test/middleware/api.js
Adds actions `blockGetParents` `blockGetSiblings` and `blockGetIndex` (though could probably dispose of the latter... thoughts?)
Moves `blockGetSequence` back to a promise
Updates API test + window location retrieval (for production build)
=> Orchestrator actions

Dockerfile
Test by doing the following:
1) stop redis, stop all containers, and clear all your previous containers and images (probably overkill, but that's what I do)
```
sudo service redis-server stop
docker kill $(docker ps -q)
docker rm $(docker ps -a -q)'
docker rmi $(docker images -q)'
```
2) 
```
docker-compose up
```
3) open 0.0.0.0:3000
=> added missing requirements to dockerfile

docker-compose-prod.yml, docker-compose.yml
These changes are needed to align with the new build process which will expect the container to have its "native" port exposed (e.g. 3000) and not port 80. Also the name of the docker image won't (at last for now) have the environment name on it.
=> Updated compose files with ports and new image name

Dockerfile, package.json
Everyone will need to install npm3 locally after merging. Realistically, this doesnt cause any changes yet, except to speed things up a bit, as dependencies are now installed maximally flat
=> update to npm3 - requires local update

package.json, src/actions/blocks.js, src/containers/GlobalNav.js, src/containers/graphics/views/constructviewer.js, src/models/Instance.js, src/schemas/Instance.js, src/schemas/Metadata.js, src/schemas/Parent.js, src/schemas/Project.js, src/schemas/fields/index.js, src/schemas/fields/validators.js, src/selectors/projects.js, test/actions/blocks.js, test/models/Block.spec.js, test/models/Instance.spec.js, test/schemas/Parent.spec.js, test/schemas/SchemaDefinition.spec.js, test/schemas/_examples.js
`parent` schema update to form `{id: <id>, sha: <sha>}` where SHA is a git SHA, the version for the project, or the project version for a block.
Update blockClone() to require projectVersion as argument, add selector to get projectVersion, update constructviewer.js cloning. Update tests.
=> Parent schema update

.dockerignore, Dockerfile, bin/local-auth.sh, docker-compose-quickstart.yml, package.json
This commit attempts to fix the issue where the genome-designer application cannot pull the authentication module from git.autodesk.com on startup in the dev/qa/prod environments in AWS. It includes:
* `server-auth.sh` was copied to `local-auth.sh`, which should be used when testing real authentication locally since local environments generally can't access s3
* install the aws cli into the genome-designer Docker image
* `server-auth.sh` was changed to use s3 to get the authentication module
* added a .dockerignore file to avoid copying the node_modules directory (and other files) into the docker image, speeding up building the Docker images locally
* changed default command for the genome-designer Docker image to `npm start` so the container runs when it may not have access to s3
* …
=> pull auth package from s3 in dev/qa/prod; docker improvements

docker-compose-quickstart.yml
This fixes the command spec for the quick-start configuration and defines the Authentication REST API endpoint via an environment variable.
=> fix bad command spec and add ENV variable for auth API end-point

src/components/InputSimple.js, src/components/InspectorBlock.js, src/components/InspectorProject.js, src/components/Inventory/InventoryItem.js, src/components/Inventory/InventoryList.js, src/containers/graphics/dnd/dnd.js, src/inventory/andrea.js, src/inventory/examples/exampleWithAnnotations.js, src/reducers/testProject.js, src/store/undo/ActionTypes.js, src/store/undo/SectionManager.js, test/store/undo/SectionManager.spec.js
Wraps inspector changes (blocks and projects) in transactions
Wraps block drag-drop in transaction
undo/redo/jump end the current transaction. This may need some tuning in the future if it presents problems. But we dont want to clobber the state after you undo with the temporary / incomplete transaction state. therefore, commit / abort in undo manager do not error when not in a transaction.
=> Transactions

docker-compose-quickstart.yml
This change isn't urgent, but will be necessary when User Authentication is required for QA and Production environments.
`auth.bionano.bio` and `auth.dev.bionano.bio` point to the same internal IP address in AWS and are private DNS records available only in Bionano AWS VPC Networks.
=> use private DNS for Authentication API HTTP endpoint

bin/local-auth.sh, bin/server-auth.sh, docker-compose-quickstart.yml, server/devServer.js, src/middleware/api.js, src/middleware/rejectingFetch.js
Fixes auth error messaging and the password reset functionality by:
* handle >=400 statuses before parsing JSON from response to propagate error messages properly
* use new functionality in bio-user-platform to override the default password reset form
=> fix Auth error messages and password reset functionality

Dockerfile
Seeing build error code of 100 from apt-get install xxx 
This is suggested solution for that: http://askubuntu.com/questions/609223/why-does-this-apt-get-command-work-in-one-context-but-not-the-other
Suspect that now that Jenkins is cleaning up images nightly, build hit this error as it was relying on pre-existing volumes that had performed apt-get update in previous builds.
=> added apt-get update to fix build when cached docker layers do not exist

src/actions/blocks.js, src/actions/projects.js, src/index.js, src/store/configureStore.js, src/store/index.js, src/store/pausableStore.js
Adds a store enhancer so you can pause the store from updating subscriptions, and allows you to dispatch actions to pause / resume. Should have no other side effects.
Applies these actions in some costly operations e.g. loading projects, cloning many blocks, etc.
=> Performance - ability to pause store updates

server/server.js, src/components/Menu/Menu.js
I suspect JSONParsers in other routes are ignored or overwritten. 
Setting the limit here fixes the issues for project save and probably other routes as well.
Also, give menu items an index to avoid console warning etc.
=> set global body size limit.

src/containers/App.js, src/containers/Inspector.js
Best we can do is remove some items from the tab order e.g. the inspector open / close buttons.
However, focus will still be attached to various not interactive elements including:
- Parts of the browser chrome ( e.g. nav bar, toolbars ). Might take 2 or 3 tabs to get back to the app.
- Parts of the onion.
We should open a card for the Onion to ensure tabindex = -1 is set on all buttons/anchors and that his hidden input that he uses for the clipboard does not get focus either.
=> remove tab focus from inspector buttons

src/components/genbank/import.js
This artifact was only on the import genbank/csv dialog. Just some rogue markup that was interpreted as text in html.
=> remove rogue markup wrapping import genbank dialog

src/components/Inspector/InspectorBlock.js, src/models/Block.js
@duncanmeech need to update construct viewer so that symbols are not shown on blocks that are constructs i.e. they have components. There is a function on blocks Block.isConstruct() to check if its a construct. There should not be a lot of scenarios where you have that (since blocks get pushed down from the construct, but just in case)
=> can't change symbol in inspector for constructs

src/actions/blocks.js, src/containers/graphics/views/constructviewer.js
Identical to regular blocks now. If the target block has sequence it will get pushed down along with the new block. If the block is empty ( e.g. [New Construct] ) then it will just get added to the end of the blocks current components.
=> make dropping of sbol block identical to regular blocks

server/data/index.js, src/actions/orders.js, src/inventory/andrea/templates.js, src/middleware/order.js, src/models/Instance.js, src/models/Order.js, src/schemas/Block.js, src/schemas/BlockSource.js, src/schemas/Order.js, src/schemas/OrderConstruct.js, src/schemas/OrderConstructComponent.js, src/schemas/OrderParameters.js, src/schemas/OrderStatus.js, src/schemas/fields/createFieldType.js, src/selectors/blocks.js, src/store/orchestrator.js, test/middleware/rollup.js, test/schemas/Block.spec.js, test/schemas/_examples.js
Lots of changes to order schema, some stubs for ordering middleware, updates to order actions to accomodate new flow:
0 - project is spec (there is a block selector to check each construct)
1 - click order
2 - create an order using `orderCreate()`
3 - open modal, change some things, click submit
4 - from modal, update order with name + order parameters (`orderSetParameters()`)
5 - generate combinations using order (`orderGenerateConstructs()`)
6 - review constructs on second page of modal
7 - submit the order (`orderSubmit()`)
8 - order goes to server, which sends to foundry, and if successful, snapshots project, sets projectVersion, sets userId, saves the order, returns to client
9 - show confirmation order modal 
----
Example flow (from console) to get combations:
```js
let projectId = …
```
=> Order schemas

src/inventory/egf/parseResults.js, src/inventory/igem/parseResults.js, src/models/Block.js
was removing source for iGEM and EGF before because they called setSequence when parsing results. allows them to maintain the source when setting sequence.
=> block.setSequence can persist source, persist IGEM + EGF sources

docker-compose-quickstart.yml, server/utils/filePaths.js
This change will only affect dev and qa environments, which have already been provisioned with a separate, persisted storage volume that can be snapshotted and expanded as necessary.
=> use external storage volume for projects in dev/qa

src/containers/graphics/views/layout.js
This shows the first option if none is selected. But it's not very convincing. You should ensure that when removing an option from a list block that, if it is the focused option, the focus is also reset.
=> default to first option selected if none is selected

data/egf_parts/project.js, server/auth/userSetup.js, server/data/persistence.js, server/data/rollup.js, src/actions/projects.js, src/components/Inventory/InventoryProject.js, src/containers/GlobalNav.js, src/containers/ProjectPage.js, src/utils/rollup/rollupFromArray.js, src/utils/rollup/rollupWithConstruct.js, test/utils/rollup.js
- rollup utils in their own folder for creating new rollups
- sets up empty project for a new user
- update projectLoad to handle opening another project if it fails. update global nav deleting and project page opening projects
=> Projectload retry

server/auth/userSetup.js, server/data/querying.js, test/server/data/querying.spec.js
querying user projects uses spawn rather than exec, does not error when user has no projects. add a test
includes part of #590 (merge that first)
=> Projects querying with grep doesn't error

src/components/authentication/userwidget.js
App is lots of issues related to holding onto previous owners data when signing out as one persona then back in with a different one. This addresses by forcing a page reload on sign out.
=> refresh page on sign out to ensure store data is cleared

docker-compose-quickstart.yml
Our Docker Hosts are configured globally to use the Fluent Log Driver, which isn't currently working. This change will explicitly tell Docker to use the json-file format for logging when starting the application so that logs can be viewed locally on the machine.
=> force docker json-file logging

src/actions/blocks.js, src/components/Inventory/InventoryRoleMap.js, src/models/Block.js
Includes #632 
Dragging in a hidden block makes it unhidden.
Alphabetize roles in role map of inventory.
=> Show hidden blocks on drag-drop

plugins/convert/genbank/genbank_export.py, plugins/convert/genbank/genbank_import.py, plugins/convert/genbank/index.js, plugins/convert/import.js, src/models/Annotation.js, src/models/Block.js, src/models/Immutable.js, src/models/Instance.js, src/schemas/Annotation.js, src/utils/generators/color.js, test/models/Annotation.js, test/models/Instance.spec.js
All genbank imports start from the same color now.
Annotations have roles.
Annotations have colors (automatically assigned), and they roundtrip them through Genbank.
Flattened out the color attribute for the annotation. It's on the main structure, not in the metadata.
=> Several annotation enhancements.

docker-compose-quickstart.yml
Jenkins will tell CloudFormation to inject NODE_ENV into the docker-compose process, which will then inject the NODE_ENV into the docker image that runs the node process.
=> pass NODE_ENV into docker image when set by Jenkins

docker-compose-production.yml
This change fixes the HOST_URL environment variable in all environments so that email verify and password reset emails work and contain secure links.
When this change is merged into production, a change to the Jenkins production deployment job needs to be made.
=> update HOST_URL envs to fix password reset emails

docs/installation-bio-user-platform.md, docs/installation.md, package.json, tools/README.md, tools/auth-stack.js, tools/auth.js
TODO 
----
`npm run start-auth-stack`
you can pass `--PLATFORM_PATH=/path/to/bio-user-platform/` if its not sibling with genetic-constructor (i.e. also in one directory below GC project root)
can pass `--DEBUG` to log output from all processes
=> add script for starting up auth + storage platform in spawned processes

src/models/Block.js, src/schemas/Block.js, src/selectors/blocks.js, test/models/Block.spec.js, test/models/Instance.spec.js, test/store/autosaving.js
e.g. on blockFlattenConstructAndLists()
also, speed up autosaving tests
=> Block.clone fix - dont reset IDs

src/containers/graphics/mousetrap.js, src/containers/graphics/views/layout.js
If the focused option is not present in a list block, default to showing the first one as select but DO NOT actually change the focus.
Note - this should speed up project loading significantly
When mousetrap module gets any mouse down event, blur and textarea or input with the focus.
=> do not change focus of option elements

src/selectors/blocks.js
Relaly fix focusGetBlockRange() to handle all peers
Fix
Update of #679
=> ok really fix focus getting range

server/auth/userSetup.js, src/containers/homepage.js, src/styles/constructviewercanvas.css
When create a new user, create the sample projects in sequence, so the empty project has a later saved-by date, so it is always opened first (instead of the template project)
Fix
EGFAD-741 #close
EGFAD-791 #close done! #done
none
slightly slower user creation, since projects created in series rather than parallel.
=> create projects on register in sequence, so return empty project

src/styles/InventoryListGroup.css
Elide long inventory names when groups (e.g. constructs), to match inventory items
UI
EGFAD-961
=> elide very long inventory item names

src/actions/focus.js
Attempting to set focused block Ids when actually pass a construct will do nothing.
Bug Fix
EGFAD-944 #code
n/a
In future, should better check if a construct was passed (not just current one), and ensure all blocks are in the same construct.
=> prevent focusing blockId when its a construct

server/extensions/index.js, server/extensions/native/fasta/README.md, server/extensions/native/fasta/index.js, server/extensions/native/fasta/package.json, server/extensions/native/genbank/index.js, test/extensions/csv.js, test/extensions/fasta.js, test/fixtures/rollup.js, test/utils/rollup.js, test/utils/sequence.js
Add router to handle export to FASTA and one to Genbank for parity. Allows exporting of specific blocks (which must have a sequence) in a given project, e.g. for the order modal
Specific route in format:
`extensions/api/fasta/export/blocks/:projectId/:blockIds`
`extensions/api/genbank/export/blocks/:projectId/:blockIds`
These routes should be well-adapted to supporting a download in the order modal
Feature
EGFAD-931
none
=> Update export to Genbank + FASTA

src/models/Block.js, test/models/Block.spec.js
Don't allow unselecting all list block options
feature / bug fix
EGFAD-947
Can't unselect all the list options
Ensures that templates always have at least one option active
=> dont allow unselecting all the blocks

.dockerignore, .gitignore
Ignore more files when building Docker Images so that Docker images remain as small as possible.
bug fix
none
=> ignore npm packages and test ouput in root dir

README.md, docker-compose-common.yml, docker-compose-jenkins.yml, docker-compose-production.yml, docker-compose-quickstart.yml, docker-compose.yml, jenkins-config.yml
Changes references to `genome-designer` as docker images and docker compose targets to `gctor` and `webapp`. Mostly this removes redundancy in the docker image names created with docker-compose, but it also shortens names. This change can be merged in before or after the GitHub repository name is changed.
Once this change is merged in, Jenkins will build and push Docker Images for the Genetic Constructor Web Application to: https://quay.io/repository/autodesk_bionano/gctor_webapp
Configuration changes to all Docker compose files and the Jenkins configuration file. 
Anyone dependent on the old quay.io repository will no longer get updated builds.
=> change Docker image refs from genome-designer

src/actions/user.js, src/containers/GlobalNav.js, src/containers/homepage.js
When present, use the heap analytics api to associated users with the session. Occurs on homepage and in sign in/ sign up middleware
=> identify users on homepage, or when sign in/up occurs to heap analytics

package.json, server/extensions/pruneNodeModules.js
adds node script to prune node modules of extensions only to those which are not listed in package.json, not to delete them all
feature
extensions not forcibly cleared every start. should not have any effect.
supports GSL, which has a postinstall requirement to include the compiled GSL source
=> dont deleted all extension - just those not in package.json

package.json
update selenium standalone package
test dependency
to support chrome driver 2.24
does not affect build. affects end to end tests
=> Selenium Standalone -> 5.7.2

Dockerfile
Install fsharp after the app is added to Dockerfile.
fix
None
Seeing this in Jenkins: 
Reading package lists...
running sudo apt-get install mono-devel -yf
{ [Error: Command failed: /bin/sh -c sudo apt-get install mono-devel -yf
E: Unable to correct problems, you have held broken packages.
]
killed: false,
code: 100,
signal: null,
cmd: '/bin/sh -c sudo apt-get install mono-devel -yf' }
=> Modified the Dockerfile for GSL Jenkins build.

Dockerfile, extensions/gslEditor/tools/install-fsharp.js, extensions/gslEditor/tools/install-fsharp.sh
Fixes the issue of missing mono libraries for GSL execution.
Fix
None
This fixes the fact that /usr/lib/mono/4.5/mscorlib.dll was missing in the mono installation on the server. 
http://askubuntu.com/questions/600972/why-cant-i-install-mono-complete
=> GSL extension - Mono installation

src/containers/GlobalNav.js
Adjust the help links
docs
none
we are hosting detailed tutorials and user guides at readme.io now and the links should reflect that
=> updating help links in global nav

src/actions/projects.js
project Id was being set incorrectly on deleting a block
fix
na
=> Fix deleting construct error - Update projects.js

Dockerfile
The sudo command is typically not present within the context of a Dockerfile and thus, when referenced, break the docker build.
Dockerfile commands run as root (unless a USER directive has been made previously in the Dockerfile). Thus commands that require root level privilege, such as apt-get, do not need to have `sudo` in front of these commands.
Note that this is different than when these commands run interactively within a Linux shell, **unless you are running as root** within the Linux shell. 
You can see whom are you running as in Linux via the `whoami` command.
You can run interactively as root via the `sudo -i` command. When finished running root-level commands, use `exit` to stop the root-level shell and return to your normal interactive user shell. 
bug fix
None
See description …
=> removed sudo references in Dockerfile

docs/extensions/ClientExtensions.md
Fixes a typo in the [Client extensions documentation](https://github.com/Autodesk/genetic-constructor/blob/master/docs/extensions/ClientExtensions.md), causing funny syntax highlighting;
=> Remove extraneous double quote char in docs

Dockerfile, docs/installation/installation.md
Remove Dockerfile command to run fsharp as GSL server is not a part of the app server. Modified docs
Fix
None
=> Removed Dockerfile fsharp install command, modified docs

docker-compose-migrate.yml, docker-compose-quickstart.yml
This change updates the Docker image name references to the usual `gctor_webapp` from the `gctordb-webapp` that was being used before the Storage API changes were merged into `master`.
Configuration change to docker-compose files used to for deployment in AWS.
=> update image name after merge into master

src/components/Inventory/InventoryRoleMap.js
when trying to drag a frozen block (e.g. EGF) from by-kind inventory, wouldn't work. cannot change properties of frozen blocks. 
fix
=> bug fix for dragging from by-kind a frozen block

.travis.yml, Dockerfile, docker-compose-migrate.yml, docker-compose-production.yml, docker-compose-quickstart.yml, package.json, server/data/persistence/blocks.js, src/components/Inventory/InventoryRoleMap.js, storage-ext/lib/http/routes/api/blocks.js, storage-ext/package.json, storage-ext/test/http/routes/api/blocks.js, test/server/data/REST/info.spec.js, tools/checks.js, tools/copy.js
Note - includes node6 PR #1203 
These commits add special support for using `'none'` in the URI for fetching blocks by role.
`GET /api/blocks/role/:ownerId/none`
This will return all blocks for the given `ownerId` where `role` is `null` or `undefined`.
#1218
=> Support querying blocks with undefined role

Dockerfile, docker-compose-feature-quickstart.yml, docker-compose-local.yml, docker-compose.yml, storage-ext/jenkins-config.yml
These changes allow for running the GCTOR app on a different port and add a docker-compose file for deploying a different application based off of a feature branch. Once this change is into `master` I'm going to cut a branch called `feature`, which can be used to automatically deploy code to `https://gctor-feature.dev.bionano.autodesk.com`.
Deployment configuration.
#1229
=> Docker Compose changes to support feature branch in dev

src/models/Block.js
block does not lose role when goes from block (leaf)  -> construct (non-leaf)
fix (kinda)
role not reset when block goes from leaf -> non-leaf
close #1238
=> dont clear role on non-leaf nodes

.travis.yml
Stop testing travis in node 4, just test node 6 -- was eating up a lot of build time
If we want to be explicit, should update our checks.js so node 4 is not allowed
=> stop testing in node 4, use node 6

package.json, tools/auth-stack.js
The move to DB-backed project storage changes the way a user would enable DB-backed authentication for local development. The `npm run auth` target assumes a user would have the entire `bio-user-platform` application running, including DB, and then the would need to override the DB password used by GCTOR storage to save projects.
To make this more simple, I removed the `npm run auth` target; I'm probably the only person that would have a `bio-user-platform` stack running locally. I then updated the `npm run start-auth` procedure to install the authentication module from the directory to which the `bio-user-platform` user platform is cloned locally. I also fixed some log messages to make them more clear.
=> simplify local authentication start script

src/models/Block.js, tools/runServer.js
`npm run start` exits when server dies unexpectedly
fix
none
=> exit main process when server crashes in runServer()

tools/auth-stack.js, tools/checks.js
small changes to local environment automation
Docker beta versions would cause errors on startup because of RegEx parsing expecting 3 integers for the version. This is now fixed.
The auth startup uses `HOST_URL` variable from configuration instead of being hard-coded.
none
=> Config fixes for start-auth and support for beta Docker versions

package.json, server/data/router.js, server/data/routerLoaderSupport.js
Looks like @maxbates changes a few lint rules after the first loader PR was passing lint checks and got merged into `master`. These changes fix the new lint errors. 
#1266
=> more lint fixes to loader.io support changes

src/components/Inventory/InventoryGroupProjects.js, src/components/Inventory/InventoryRoleMap.js
By kind panel filters based on whether templates or not
Removes count until tab is open - no way to efficiently query at the moment based on whether in templates tab or not
fix
counts removed from by kind panel until tab is opened
n/a
close #1258
=> By kind templates

.eslintrc, src/components/Menu/MenuOverlay.js, src/styles/variables.css
Context menus reposition themselves if they fall in the bottom half of the viewport
( also I removed a lint rule...no mixed operators is dumb. Order of operations are well known. As it stands 1 + 2 * 3 would not be allowed. Lint rules should not change the language. )
=> Context menus redux

src/components/Inspector/InspectorBlock.js
No symbol picker for construct, rules for constructs was already not visible for constructs.
=> no symbol picker for top level constructs

src/containers/graphics/views/constructviewer.js
Cannot drop blocks onto hidden blocks
=> disallow adding children to hidden blocks

server/extensions/package.json
This change bumps the version of the GSL Editor to `v1.1.0`, which is compatible with the new UI elements of the new GC UX.
Fixes the menus in the GSL Editor Console
#1391
=> require new GSL Editor version for new UX

server/extensions/package.json
`v1.1.1` of the GSL Editor will detect if a GSL Project code file is empty and load the default code instead.
Bug workaround - Still unclear why GSL code profile files aren't being saved properly in some cases.
None
=> v1.1.1 of GSL Editor handles empty GSL code files gracefully

docker-compose-quickstart.yml, server/server.js, server/utils/logConfig.js
The previous logging configuration was deficient because `NODE_ENV=dev` in both the local development environment as well as the deployed `dev` environment. The deployed `dev` environment is where we want the most verbose logging. Response times were also not logged in the `production` environment.
This commit provides the following:
* ability to enable "verbose" logging in any environment with `process.env.VERBOSE_REQUEST_LOGS == 'true'`
* abbreviated request logging in local environments
* addition of response time to `production` logs
* change to ISO date format
* remove `remote address`, `remote user`, and `HTTP version` from production logs
* `remote address` is always one of the two load balancers
* `remote user` was always null
* reorder logging fields for easier filtering
feature …
=> logging improvements

src/containers/graphics/views/constructviewer.js
Shows the inspect block/construct panel ( if the inspector is open ) when selecting blocks.
Used to leave the inspector open on whatever panel the user selected.
=> Force block inspect

src/styles/ProjectHeader.css, src/styles/SceneGraphPage.css, src/styles/inline-editor.css, src/styles/inter-construct-droptarget.css
Tweak project header and squeeze first inter construct drop zone so that the first construct lines up with top of inspector / inventory.
=> Project header tweak

src/actions/blocks.js
when adding a block to a block, sets the projectid of all children 
fix
none
=> deep set projectId when add a block to a block

docker-compose-quickstart-ecs.yml
To make cut-over to ecs-deployment adding both ecs-based and non-ecs-based docker-compose file. Main difference is the usage of dynamic host ports in the ecs case. 
deployment
None
None
future PR will remove non-ecs files when cut-over is complete
=> added explicit separate compose file so ecs build can be done alongside prevous

docker-compose-feature-quickstart.yml, docker-compose-quickstart-ecs.yml, docker-compose-quickstart.yml
Change lb dns entries to always contain environment name via ".${BNR_ENVIRONMENT}."
This is the preferred change as the names for internal dns entries of the load balancer *alwasy* contain the environment entry, such as:
internal-lb.dev.bionano.bio
internal-lb.qa.bionano.bio
internal-lb.prod.bionano.bio
The prevous env entry `${BNR_ENV_URL_SUFFIX}` will collapse to an empty string prod environment. This env is meant for public facing urls.
bug fix
deployment
none
=> fix for deploy error with internal dns names to loadbalancer

jenkins-config.yml, src/components/formElements/Captcha.js
In the process of falling back from ECS for the `development` environment for the GCTOR application, the non-ECS stack had to be recreated. This introduced some backwards-incompatible changes that require the configuration update in this PR.
This PR also has the Captcha SiteKey update that was required as a result of inadvertently committing secrets to public Github. This change has already gone out to `QA` and `PROD`.
The `dev` build will NOT succeed until this PR is merged.
=> build configuration update for latest stack template version

server/extensions/native/genbank/genbank_import.py
Python was returning an array in the name, instead of the string.
=> Fixed bug with converting name in Snapgene Import

package.json, src/components/formElements/Captcha.js
`QA` was tagged with `v0.10.5` and subsequently released to `PROD` in order to accommodate the change in the Captcha secret after it was compromised.
=> merge v0.10.5 patch release tag back into master

extensions/blast/README.md, extensions/blast/blockMenuItem.js, src/actions/blocks.js, src/models/Block.js, src/models/Instance.js, test/models/Block/Clone.spec.js
- Prevent blast on list blocks / parent blocks
- remove annotations on starting blast
- Update cloning behavior to properly handle overwrites with empty arrays
- add basic docs for blast extension
replace #1735
=> Blast fixes (only run on leaf nodes)

src/containers/graphics/views/constructviewer.js
when extensions are in weird state, (e.g. not registering properly), handle block menu item extensions not rendering properly
fix
none
fixes some failing e2e tests, e.g. when blast installed improperly
=> (fix) catch when extension menu:block render function not exist

tools/start.js
setup part of script was running twice on `start-auth` due to merge regression
fix
=> fix merge error. avoid setup twice on start-auth

docker-compose-local.yml
Somehow forgot to commit a change to the main GC `docker-compose` configuration upon cleaning up the `docker-compose` configuration for the GC storage app. This broke the Jenkins build and is blocking deploys of the `master` branch to the `dev` environment.
This change updates the name of the configuration file used to run the PostgreSQL DB during unit testing in Jenkins.
Bug Fix
Fixes already broken Jenkins build.
#1782
=> BUILD FIX: fix reference to DB image in ./storage-ext

extensions/blast/blockMenuItem.js, src/components/Menu/MenuItem.js, src/components/Menu/SubMenu.js, src/graphics/views/constructviewer.js
Issue: https://github.com/Autodesk/genetic-constructor/issues/1758
This PR makes a few tweaks to the plugins context menu to make it match the spec in [zeplin](https://app.zeplin.io/project.html#pid=581d0bc0b7502238616341cb&sid=58a4ea278d3c3a5d387d7986).
=> Blast Menu UI Tweaks
